name: Cairo CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Setting up snfoundry
        uses: foundry-rs/setup-snfoundry@v3
      - name: Step 4 - Installing USC
        run: curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh -s -- v2.2.0
      - name: Step 5 - Running tests
        run: scarb test
  
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Checking format
        run: scarb fmt --check
