name: Cairo CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Testing
        run: scarb test
  
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Checking format
        run: scarb fmt --check
