name: Integration CI

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use correct node version
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.5.0
          
      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Start devnet in background
        run: scarb run start-devnet

      - name: Installing USC
        run: curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh -s -- v2.4.0

      - name: Run integration tests
        run: scarb run test-ts

  gas-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use correct node version
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.5.0
          
      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Start devnet in background
        run: scarb run start-devnet

      - name: Installing USC
        run: curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh -s -- v2.4.0

      - name: Gas report
        run: scarb run profile --check

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use correct node version
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Check correct formatting
        run: yarn prettier --check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Use correct node version
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Check correct linting
        run: yarn eslint .
